services:
  backend:
    image: flashpoint-ingest
    build:
      dockerfile: ./Dockerfile-ingest
    volumes:
      - telemetry:/app/telemetry

# if it failed to mount _data, make sure FLASHPOINT_DIR is correct and there is a FLASHPOINT_DIR/telemetry directory
volumes:
  telemetry:
    driver_opts:
      type: "none"
      o: "bind"
      device: "${FLASHPOINT_DIR}/telemetry"