"""Regenerate src/flashpoint/readers/owlet-manifest.toml from CTRE's redist index.

Usage: python tools/update-owlet-manifest.py

Takes stable channels only (no alpha/beta), the latest owlet version per hoot compliancy,
and every platform CTRE publishes. Each binary is downloaded once to compute its SHA-256;
CTRE's published SHA-1 is checked too. Ingest never contacts the index at runtime; it
only reads the committed manifest.
"""

import hashlib
import json
import sys
import urllib.request
from pathlib import Path
from typing import Any

INDEX_URL = "https://redist.ctr-electronics.com/index.json"
PLATFORMS = ("macosuniversal", "linuxx86-64", "linuxarm64", "windowsx86-64")
MANIFEST = Path(__file__).resolve().parent.parent / "src/flashpoint/readers/owlet-manifest.toml"


def _version_key(version: str) -> tuple[int, ...]:
    return tuple(int(p) for p in version.split(".") if p.isdigit())


def _digests(url: str) -> tuple[str, str]:
    sha1, sha256 = hashlib.sha1(), hashlib.sha256()  # noqa: S324 - CTRE publishes SHA-1
    with urllib.request.urlopen(url) as response:
        for block in iter(lambda: response.read(1 << 20), b""):
            sha1.update(block)
            sha256.update(block)
    return sha1.hexdigest(), sha256.hexdigest()


def build_manifest(index: dict[str, Any]) -> str:
    if index.get("JsonVersion") != "1.0.0.0":
        raise ValueError(f"unexpected index JsonVersion {index.get('JsonVersion')!r}")
    owlet = next(tool for tool in index["Tools"] if tool["Name"] == "owlet")
    lines = [
        "# Generated by tools/update-owlet-manifest.py from " + INDEX_URL,
        "# Do not edit by hand. One entry per stable hoot compliancy (latest owlet).",
        "",
    ]
    stable = [
        c for c in index["ChannelCompliancy"]
        if not any(tag in c["Name"].lower() for tag in ("alpha", "beta"))
    ]  # fmt: skip
    for channel in sorted(stable, key=lambda c: c["Compliancy"]):
        items = [i for i in owlet["Items"] if i["Compliancy"] == channel["Compliancy"]]
        if not items:
            continue
        item = max(items, key=lambda i: _version_key(i["Version"]))
        lines += [
            "[[owlet]]",
            f'channel = "{channel["Name"]}"',
            f"compliancy = {item['Compliancy']}",
            f'version = "{item["Version"]}"',
        ]
        for platform in PLATFORMS:
            url = item["Urls"].get(platform)
            if not url:
                continue
            sha1, sha256 = _digests(url)
            published = item["Urls"].get(platform + "-sha1")
            if published and published != sha1:
                raise ValueError(f"SHA-1 mismatch for {url}")
            print(f"  {item['Version']} C{item['Compliancy']} {platform}", file=sys.stderr)
            lines += [
                f'[owlet.platforms."{platform}"]',
                f'url = "{url}"',
                f'sha256 = "{sha256}"',
            ]
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    with urllib.request.urlopen(INDEX_URL) as response:
        index = json.load(response)
    MANIFEST.write_text(build_manifest(index))
    print(f"wrote {MANIFEST}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
